version: '2'

tasks:

  run:
    cmds:
      - go run src/main.go

  build:
    cmds:
      - go run tools/assets.go
      - go get -u github.com/go-bindata/go-bindata/...
      - env GOOS=windows GOARCH=amd64 go build -o build/shooty.exe -v -i src/main.go

  assets:
    cmds:
      - go run tools/assets.go
