// Code generated by file2byteslice. DO NOT EDIT.
// (gofmt is fine after generating)

package main

var packagexml = []byte("<TextureAtlas imagePath=\"atlas-1.png\">\n    <SubTexture name=\"circleWhite\" x=\"0\" y=\"0\" width=\"64\" height=\"64\"/>\n    <SubTexture name=\"enemy1\" x=\"64\" y=\"0\" width=\"32\" height=\"32\"/>\n    <SubTexture name=\"enemy2\" x=\"96\" y=\"0\" width=\"32\" height=\"32\"/>\n    <SubTexture name=\"enemy3\" x=\"128\" y=\"0\" width=\"32\" height=\"32\"/>\n    <SubTexture name=\"player\" x=\"160\" y=\"0\" width=\"32\" height=\"32\"/>\n    <SubTexture name=\"lives\" x=\"192\" y=\"0\" width=\"16\" height=\"16\"/>\n    <SubTexture name=\"bullet\" x=\"208\" y=\"0\" width=\"8\" height=\"8\"/>\n    <SubTexture name=\"starFast\" x=\"64\" y=\"32\" width=\"1\" height=\"32\"/>\n    <SubTexture name=\"starSlow\" x=\"65\" y=\"32\" width=\"1\" height=\"32\"/>\n</TextureAtlas>\n")
